language: python

before_install:
- pip install --upgrade pip
- pip install --default-timeout 60 tox
# Travis-CI apparently has this built-in and no upgrade is done when our setup runs
- pip install --upgrade pytest>=3.4.0

jobs:
    include:
        - python:
            - 3.6
          script: tox -e py36
        - python:
            - 3.7
          script: tox -e py37
        - python:
            - 3.8
          script: tox -e py38
        - python:
            - 3.9
          script: tox -e py39
        - python:
            - 3.6
          script: tox -e flake
        - install: pip install --quiet --default-timeout 60 coveralls
          script: tox -e cover
          after_script: coveralls
